# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWz2no-rpZnzMHEqcXyRCa46KTb-Kzuj
"""

import cv2

# Reading the image
image_path = 'pink.jpg'
image = cv2.imread(image_path)

# Converting the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Inverting the image
inverted_gray_image = 255- gray_image

#Blurring the image by gaussian function
blurred_image = cv2.GaussianBlur(inverted_gray_image, (21, 21), 0)

#Inverting the image
inverted_blurred_image = 255 - blurred_image

#Converting the image into sketch
pencil_sketch = cv2.divide(gray_image, inverted_blurred_image, scale=256.0)

cv2.imshow("Original Image", image)
cv2.imshow("Pencil Sketch", pencil_sketch)
cv2.waitKey(0)
cv2.destroyAllWindows()